### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by AlxndrJhn** [AlxndrJhn/DLF-Nova-Play-My-Own-Music#7]
- [ ] remove unused mocker 
- [ ] replace placeholders in tests for failing interfaces
- [ ] mention ffmpeg installation in Readme
